### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by rexlManu** [ReflxctionDev/cub#5]
I would suggest that a command with subcommand the main command should be a help command with all subcommands displayed and they description if they had one. Maby add a permission check that only that subcommands get displayed that he has access.

It would also be nice to add a usage information for the parameter.
As example:

Command: /game create <name>

On command /game help
Output:

/game create <name>
-> Description

On command /game help create

Output:

/game create <Name>
- Name must be a string

**Comment by Revxrsal** [comment]
As a start, you can use [\@CatchInvalid](https://github.com/ReflxctionDev/cub/blob/master/common/src/main/java/io/github/revxrsal/cub/annotation/CatchInvalid.java) to implement such a thing, however a help-menu API is indeed needed. I will update this issue as the API gets implemented.

**Comment by Revxrsal** [comment]
A basic help API has been implemented in https://github.com/ReflxctionDev/cub/commit/2205885c9e9bad1a744827435fea36896eb034f4. Will be awaiting feedback.

As for your usage information, you can implement this using the [CommandExceptionHandler](https://github.com/ReflxctionDev/cub/blob/master/common/src/main/java/io/github/revxrsal/cub/exception/CommandExceptionHandler.java) (check docs). What you see is simply the [default implementation](https://github.com/ReflxctionDev/cub/blob/master/bukkit/src/main/java/io/github/revxrsal/cub/bukkit/core/DefaultExceptionHandler.java).
