### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by roccodev** [ReflxctionDev/cub#6]
Hello there!
Currently your project is [missing a license](https://choosealicense.com/no-permission/), which restricts the ways it can be used and included in other projects. 

I'd greatly recommend adding a license, and due to the nature of the project, I'd like to suggest the [MIT License](https://choosealicense.com/licenses/mit/), which is very permissive.

If you instead care about contributions and would like to get the improvements other people may make to your library, you can use the [GPLv3](https://choosealicense.com/licenses/gpl-3.0/). Note that this will prevent people that distribute their software from using alternative licenses, if that behavior is undesirable you can then opt for the [LGPLv3](https://choosealicense.com/licenses/lgpl-3.0/), which still requires people to share their contributions to your library under the GPL, but poses no restrictions on the work the library is used in.

**Comment by Revxrsal** [comment]
Hello. Thank you for your notice. I've added the license in https://github.com/ReflxctionDev/cub/commit/741984e1b7802dc4abc8f6738d54867a5dcf8859. 

From what I can see on MIT's licensing conventions, only the license text file needs to be present, and does not need a reference in every source file, hence I'll settle for adding the LICENSE file.
